name: Readme
on:
  push:
    branches:
      - main
      
defaults:
  run:
    shell: bash

jobs:
  Update-Contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Aggiornamento contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.4
        with:
          use_username: true
          committer_username: "TryKatChup"
          commit_message: "update README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}